--
-- PostgreSQL database dump
--

-- Dumped from database version 10.1
-- Dumped by pg_dump version 10.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;
SET row_security = off;

SET search_path = public, pg_catalog;

--
-- Data for Name: lostpets; Type: TABLE DATA; Schema: public; Owner: cristina
--

COPY lostpets (lost_pet_id, lost_pet_name, species_code, breed_code, lost_pet_gender, user_id, lost_pet_color, description, datetime, photo, latitude, longitude, address, url, title, phone, email) FROM stdin;
1	\N	c	\N	\N	\N	\N	Our cat Totoro has been missing since last night on Shoal Drive, San Mateo. He's a medium size, short hair, grey mixed Siamese cat with blue eyes, and a raccoon like tail. He's very talkative, sweet and a little shy. He might be hiding in your backyard or garage. If you have seen him or even better, have him, please contact us at. We really appreciate your help!	2018-01-10 19:03:35.08	https://images.craigslist.org/00505_8vgKdyJERK0_600x450.jpg	37.560857	-122.290598	1010 Shoal Drive	https://sfbay.craigslist.org/pen/laf/d/grey-semi-siamese-cat-missing/6455395279.html	Grey Semi-Siamese Cat Missing in San Mateo/Foster City	\N	\N
2	\N	d	\N	\N	\N	\N	3 easy steps to finding your lost pet or re-uniting a found pet with its owner. Take advantage of our FREE and/or paid services.We're here to help make sure you do everything reasonably possible to bring your lost dog or missing cat home.lost pet details	2017-12-18 00:49:17.08	\N	\N	\N	{}	https://sfbay.craigslist.org/pen/laf/d/lost-or-missing-dog-locating/6429565464.html	A lost or missing dog locating service...Our alert lost pet service	\N	\N
3	\N	c	\N	\N	\N	\N	My cat JUNIOR (a 4 year old male) has gone missing. He is white with gray/black spots on his body. He has 2 distinct spots that sit on top of both his ears. He has a tail that looks like a raccoon. He is very friendly and loves people! Last seen was near my home in Richmond. He is chipped and neutered. If you do see him please give me a call: Thank you. (in the picture his paw looks black but its very pink) He likes to be outside a lot. I AM OFFERING A REWARD FOR HIS RETURN !!! $$$$	2018-01-08 15:01:31.08	https://images.craigslist.org/01717_dVOdStGQLu7_600x450.jpg	37.9265	-122.3342	{}	https://sfbay.craigslist.org/eby/laf/d/please-help-missing-white/6452694793.html	PLEASE HELP *** MISSING WHITE MALE CAT *** REWARD!	\N	\N
4	\N	c	\N	\N	\N	\N	An adult female dark Siamese cat with slightly noticeable stripes on top of her upper back head has been missing since July 19t, 2017 around 2am on Lilac alley between 24th Street and 25th Street. She is NOT AN ALLEY CAT and IS NOT A STRAY. We have owned her for over 9 years. She is very scared of strangers and meows a lot. She is spayed and has a microchip.No questions asked if she is returned back to us. My family and I miss her so much.	2018-01-08 16:51:31.08	\N	37.750935	-122.417779	Lilac	https://sfbay.craigslist.org/sfc/laf/d/reward-for-my-lost-siamese-cat/6452811617.html	REWARD FOR MY LOST SIAMESE CAT!	\N	\N
5	\N	c	\N	\N	\N	\N	Lost Cat Brothers: One Black, One Yellow. El Cerrito near Korematsu  Middle School.Please call if you see either one of these cats.  They are brothers and may be together.	2018-01-08 17:08:30.08	\N	37.920724	-122.30488	Donal Ave at Lawrence	https://sfbay.craigslist.org/eby/laf/d/lost-cat-brothers-one-black/6452828301.html	Lost Cat Brothers: One Black, One Yellow. El Cerrito near Korematsu	\N	\N
6	\N	c	\N	\N	\N	\N	Friendly, older, long-haired black/dark brown, Maine Coon mix, indoor kitty somehow wandered from our premises. We're on Southridge Way, on the Southern Hills, cross street is Oakridge. He's slow moving so we don't know how he got out. His name is Bear, and he is chipped. We moved here recently, so he is totally unfamiliar with this environment. He needs medication every day, so we're worried. If you see Bear, please call Chris	2018-01-08 07:43:16.08	\N	37.705932	-122.428282	Southridge Way at Oakridge	https://sfbay.craigslist.org/pen/laf/d/lost-black-male-cat/6452041500.html	Lost- Black male cat	\N	\N
7	\N	c	\N	\N	\N	\N	Our Tortis Shell CAT, named Terra, disappeared from home Monday, 9/16/14.She is a shy indoor cat, is litter box trained, spayed, and generally prefers dry cat food.We really miss her, please call us at if you see her or anything.	2018-01-03 08:42:46.08	https://images.craigslist.org/00X0X_l1Qcwg0j0iz_600x450.jpg	37.946363	-122.016907	 (concord / pleasant hill / martinez)	https://sfbay.craigslist.org/eby/laf/d/lost-tortis-shell-cat-female/6446453890.html	Lost Tortis Shell Cat - Female, altered	\N	\N
8	\N	c	\N	\N	\N	\N	Calico cat last seen 32nd ave and Lincoln wayBlack patch over left eye , Orange patch over right eyeWhite chest   $1000 reward	2018-01-08 14:53:55.08	https://images.craigslist.org/00r0r_7oPUgELKfzM_600x450.jpg	37.762386	-122.489426	5432 Geary Boulevard	https://sfbay.craigslist.org/sfc/laf/d/cat-multi-color-lost-1000/6452685747.html	CAT MULTI COLOR LOST    $1000 reward	\N	\N
9	\N	c	\N	\N	\N	\N	He has been gone since night time, 11/16/17, around Elston or Coronado, near Skyline and Sharp Park. He is an orange tabby, 2 years old, 15 lbs, larger sized in length, medium in girth. Name is Ridley. Collar is missing on him. He is neutered and chipped. Please contact me if you have seen him. Please hold on to the potential cat until we see him.  Or bring him directly to the Peninsula SPCA. Thank you!!	2017-12-22 16:47:34.08	\N	37.6247	-122.429	 (san bruno)	https://sfbay.craigslist.org/pen/laf/d/missing-male-cat-kitty/6435416108.html	Missing Male Cat / Kitty	\N	\N
10	\N	c	\N	\N	\N	\N	* Sophie has been missing since 8/10/17* Female Siamese/Manx mix - ~6.5 lbs - almost 13 years old* Sophie is microchippedPlease snap a picture and call me if you see her!!!  Thank you so much!!!	2018-01-08 09:55:56.08	https://images.craigslist.org/00k0k_85eZvYCjXME_600x450.jpg	37.289942	-121.942667	Salmar Avenue at Harrison Avenue	https://sfbay.craigslist.org/sby/laf/d/lost-cat-no-tail-1000-reward/6452247904.html	LOST CAT, NO TAIL ***$1,000 REWARD***	\N	\N
11	\N	c	\N	\N	\N	\N	Near Morehead Auto.	2018-01-08 07:43:52.08	https://images.craigslist.org/00d0d_4WgCbULVKK0_600x450.jpg	38.2671	-122.0357	 (fairfield / vacaville)	https://sfbay.craigslist.org/eby/laf/d/lost-cat-armijo-area/6452042318.html	Lost Cat.   Armijo area	\N	\N
12	\N	c	\N	\N	\N	\N	Hello everyone,My sweet kitty Felix went missing early Sunday Morning from this Central Santa Clara neighborhood. He is very scared and will most likely be hiding away somewhere. He might have even run into a neighbors garage to hide in there or under a car. If you think you may have seen him, or have any information, please give me a call/text/email. We would love to have him back home soon, especially with all this rain and cold weather :( Please keep an eye out on this neighborhood! Thank you so much!!!	2018-01-08 11:18:29.08	https://images.craigslist.org/00D0D_3XEyAL9nlO6_600x450.jpg	37.342066	-121.985943	947 Quince Ave	https://sfbay.craigslist.org/sby/laf/d/lost-catblack-white-male-cat/6452379094.html	LOST CAT!Black/White male cat lost in Santa Clara!Please help find him	\N	\N
13	\N	c	\N	\N	\N	\N	Gray Kitty is still missing. Last seen 10/29/2015 Snell and Santa TeresaIf you have found him and rehomed him,please let me know so I can stop looking and worring.Thank you	2017-12-24 00:28:32.08	https://images.craigslist.org/01212_helVvRpQeCm_600x450.jpg	37.245341	-121.830768	Snell at Tuscarora CT	https://sfbay.craigslist.org/sby/laf/d/cat-still-missing-grey/6436560008.html	Cat Still Missing Grey	\N	\N
14	\N	c	\N	\N	\N	\N	Gray Kitty is still missing. Last seen 10/29/2015 Snell and Santa TeresaIf you have found him and rehomed him,please let me know so I can stop looking and worring.Thank you	2017-12-24 00:23:02.08	https://images.craigslist.org/01212_helVvRpQeCm_600x450.jpg	37.245341	-121.830768	Snell at Tuscarora CT	https://sfbay.craigslist.org/sby/laf/d/cat-still-missing-gray-white/6436558788.html	Cat Still Missing Gray & White	\N	\N
34	\N	d	\N	\N	\N	\N	I lost my service dog today. His name is Rusty and he helps with my PTSD. Please help.	2018-01-06 19:03:22.08	https://images.craigslist.org/00P0P_aTq5Cdp1I0G_600x450.jpg	36.9721	-121.9881	 (santa cruz)	https://sfbay.craigslist.org/scz/laf/d/lost-dog-reward/6450673968.html	Lost Dog - REWARD	\N	\N
15	\N	c	\N	\N	\N	\N	MY cat Baby went missing after new years we think the fire works might have scared and made her run away. She's blind so her eye's are really cloudy almost foggy looking She is black and white,has a little white spot on her mouth,white feet and her ear is clipped from the spca .She is also wearing a pink reflective collar and a grey seresteo flea collar. Where scared that due to her not being able to see she won't be able to make it back home on her own. she went missing in Hayward 94544 up the street from Mt Eden high school She likes to go into back yards maybe trees we already went down to the spca they told us that they haven't seen any cats that look like that we will be back Tuesday to check if anyone has seen her. if anyone see's her or hears anything please give me a call no matter what time it is day or night we are willing to pay a cash reward!!! joe Thank you for your time.	2018-01-07 03:09:45.08	\N	\N	\N	 (hayward / castro valley)	https://sfbay.craigslist.org/eby/laf/d/lost-black-and-white-blind-cat/6450835597.html	LOST BLACK AND WHITE BLIND CAT!!!!	\N	\N
16	\N	d	\N	\N	\N	\N	Nala has been missing since 8/25/2016. She is a 7 year old, 8 lb. female and spayed Shih Tzu mix. Her main color is cream with some light gray in the face, ears, back and tail.  She has a microchip.  She was lost near Trieste Ct. and Oswego drive in San Jose. We miss her badly and reward will be given with no questions ask.  E-mail Ness or call/text at (4-zero-8)256-7000.  PLEASE HELP!	2018-01-05 18:15:39.08	https://images.craigslist.org/00i0i_ZQcaDYfQah_600x450.jpg	37.322841	-121.852664	Trieste Ct. at Oswego Dr.	https://sfbay.craigslist.org/sby/laf/d/reward-for-return-of-lost/6449529667.html	$5,000.00 REWARD FOR RETURN OF LOST/MISSING DOG (SHIH TZU MIX)	\N	\N
17	\N	c	\N	\N	\N	\N	Lost Black Cat named Binx. He is an all black male cat last seen on the corner of Connecticut and Hampton on Monday June 26th. He has a bent/crooked tail and was wearing an orange collar. Please contact with any information! Large Reward to get him home safe!	2017-12-26 11:45:25.08	https://images.craigslist.org/00V0V_jRze6TrseLJ_600x450.jpg	37.459769	-122.235657	Hampton at Connecticut	https://sfbay.craigslist.org/pen/laf/d/lost-black-cat-reward/6438337910.html	Lost Black Cat-reward!	\N	\N
18	\N	d	\N	\N	\N	\N	I haven't given up hope that my 5 year old, Female/Spayed Queensland Heeler can be found and re-united with her family. She escaped on September 22, 2017 from a facility in Walnut Creek near Heather Farms Park & John Muir Hospital. She ran down the Canal Trail so could be anywhere in Contra Costa County. We have searched frantically for her...Facebook, Fido Alert, Claycord.com, Craigslist, Martinez Animal Services, veterinary hospital, signs & posters around Walnut Creek...NOTHING. I am starting to believe someone took her in and is not doing the right thing by bringing her in to be scanned for a microchip. She is micro-chipped and wearing a cowhide leather collar with pink rhinestones. Her name is Dallas and she was rescued from a shelter in Temecula, CA. She is timid and scared of strangers due to her past life in Temecula. Her family wants and needs her back. Please, if you know anyone in this area of Contra Costa County who has seen this dog or heard of someone who found a dog matching this description, please contact me. No questions asked. Thank you!!	2018-01-03 14:19:52.08	https://images.craigslist.org/00p0p_jxGZwjZ0sTw_600x450.jpg	37.917524	-122.039845	1780 Ygnacio Valley road	https://sfbay.craigslist.org/eby/laf/d/lost-queensland-heeler-dog/6446933365.html	Lost Queensland Heeler Dog- Owner's not giving up hope.  Anyone seen?	\N	\N
19	\N	d	\N	\N	\N	\N	Our beloved Theo has been missing since February 13th. He is our baby. We just want him back. Please PLEASE Call or text or reply to this email. NO QUESTIONS ASKED!!! REWARD $3,500 PLEASE CALL/TEXT JIM:Theo ran away from the dog sitters at 5pm on 2/13 He was last seen at 1146 Blossom Hill Road In San Jose, Ca. 95118. Any information or if you think you've seen him:WE JUST WANT HIM HOME! god bless!> Brussels Griffon (Black & Tan) Looks like Yorkie> Male> Microchipped> Approx. 10 Pounds> 1 Years Old> Pug-like Nose> Snaggle Tooth> Docked Tail> Old wound on back> Theo	2018-01-03 19:04:00.08	https://images.craigslist.org/00707_761eJbSFQcS_600x450.jpg	37.2458	-121.8306	 (los gatos)	https://sfbay.craigslist.org/sby/laf/d/missing-dog-3500-reward/6447201213.html	missing DOG $3,500 REWARD!	\N	\N
20	\N	d	\N	\N	\N	\N	Our beloved Theo has been missing since February 13th. He is our baby. We just want him back. Please PLEASE Call or text or reply to this email. NO QUESTIONS ASKED!!! REWARD $3,500 PLEASE CALL/TEXT JIM:Theo ran away from the dog sitters at 5pm on 2/13 He was last seen at 1146 Blossom Hill Road In San Jose, Ca. 95118. Any information or if you think you've seen him:WE JUST WANT HIM HOME! god bless!> Brussels Griffon (Black & Tan) Looks like Yorkie> Male> Microchipped> Approx. 10 Pounds> 1 Years Old> Pug-like Nose> Snaggle Tooth> Docked Tail> Old wound on back> Theo	2018-01-03 19:05:05.08	https://images.craigslist.org/00707_761eJbSFQcS_600x450.jpg	37.2458	-121.8306	 (los gatos)	https://sfbay.craigslist.org/sby/laf/d/3500-reward-for-the-return-of/6447202010.html	$3500 Reward for the return of our Missing Brussels Griffon DOG	\N	\N
21	\N	d	\N	\N	\N	\N	Theo ran away from the dog sitters at 5pm on 2/13 He was last seen at 1146 Blossom Hill Road In San Jose, Ca. 95118. Any information or if you think you've seen him or KNOW someone who has him??Please email/call/text Jim at: or reply to this email.NO QUESTIONS ASKED! $3,500 REWARD for his returnWE JUST WANT HIM HOME! god bless!> Brussels Griffon (Black and Tan) Looks like Yorkie> Male> Microchipped> Approx. 10 Pounds> 1 Years Old> Pug-like Nose> Snaggle Tooth> Docked Tail	2018-01-03 19:04:51.08	https://images.craigslist.org/00A0A_l4UjKs4KHQI_600x450.jpg	37.3688	-122.0363	{}	https://sfbay.craigslist.org/sby/laf/d/3500-reward-for-the-return-of/6447201857.html	$3500 Reward for the return of our Missing Brussels Griffon DOG	\N	\N
22	\N	d	\N	\N	\N	\N	We just got a call about a sighting yesterday in the mid afternoon. Happy was on Lasuen Ct. in Los Gatos. (Blossom Hill Rd and Union Ave area) Please keep a lookout for a small white Maltese. (See picture)We need help searching the neighborhoods around Safeway on Union, Union Middle School and the area to the East of Union Ave near Anne Way. Please help.Call Jeff at if you have any questions or have more information.Original post;We lost  our white Maltese mix dog in Los Gatos. A friend was walking our dog in Heintz open space area above Regent Dr. on Tuesday afternoon. We have a possible sighting yesterday at the Walgreen's/Starbucks parking lot on Blossom Hill Road and Harwood Rd. If you have any sightings or information, please call Jeff at.	2018-01-04 07:20:25.08	\N	37.23272	-121.927471	118 Regent Dr	https://sfbay.craigslist.org/sby/laf/d/lost-small-white-dog-in-los/6447526197.html	Lost Small White Dog in Los Gatos area	\N	\N
35	\N	d	\N	\N	\N	\N	Nala has been missing since 8/25/2016. She is a 7 year old, 8 lb. female and spayed Shih Tzu mix. Her main color is cream with some light gray in the face, ears, back and tail.  She has a microchip.  She was lost near Trieste Ct. and Oswego drive in San Jose. We miss her badly and reward will be given with no questions ask.  E-mail Ness or call/text at (4-zero-8)256-7000.  PLEASE HELP!	2018-01-07 08:13:05.08	https://images.craigslist.org/00i0i_ZQcaDYfQah_600x450.jpg	37.322841	-121.852664	Trieste Ct. at Oswego Dr.	https://sfbay.craigslist.org/sby/laf/d/reward-for-return-of-lost/6451002154.html	$5,000.00 REWARD FOR RETURN OF LOST/MISSING DOG (SHIH TZU MIX)	\N	\N
23	\N	d	\N	\N	\N	\N	My roommates beautiful Australian Shepherd, female 6yo - name is Georgia - was lost by a family we left the dog with over the holidays. They offer dog housing services via Rover and lost her. Unreal. They live here: 563 Rainwell Dr, San Jose. Please help me find her. She is a beautiful dog, picture attached, and is the sweetest dog ever. She's fast but responds to friendly calling of her name and loves rubs on her back. If you see her, please call me immediately -. Correct number, I'm a transplant from Charlotte. Her tags are to my roommate Jeff Evey. They say Maricopa, Arizona but she lives in Santa Clara. She is also chipped. I love this dog more than anything in California so any information or help would be greatly appreciated in her safe return to our home. Reward for her safe return.	2018-01-04 14:13:14.08	\N	\N	\N	 (san jose east)	https://sfbay.craigslist.org/sby/laf/d/lost-dog-1k-reward-australian/6448101953.html	Lost dog, $1k reward, Australian Shepherd, shepard, shephard, Aussie	\N	\N
24	\N	d	\N	\N	\N	\N	Black Lab Mix Female Dog 35 lbs - answers to Frida. She ran off from her dog walkers January 11th in McLaren Park in San Francisco.If you have found her or see that someone else has - please call or text with a picture and video. There is a $2,500 reward for her safe return.Her family misses her tremendously!!!Thank you!	2018-01-05 08:29:42.08	https://images.craigslist.org/00V0V_5A2rjwaqnEU_600x450.jpg	\N	\N	{}	https://sfbay.craigslist.org/sfc/laf/d/black-lab-mix-female-dog-lost/6448792528.html	Black Lab Mix Female Dog Lost - ***$2,500 Reward***	\N	\N
25	\N	d	\N	\N	\N	\N	Black Lab Mix Female Dog 35 lbs - answers to Frida. She ran off from her dog walkers January 11th in McLaren Park in San Francisco.If you have found her or see that someone else has - please call or text with a picture and video. There is a $2,500 reward for her safe return.Her family misses her tremendously!!!Thank you!	2018-01-05 08:32:22.08	https://images.craigslist.org/00V0V_5A2rjwaqnEU_600x450.jpg	\N	\N	{}	https://sfbay.craigslist.org/sfc/laf/d/black-lab-mix-female-dog-lost/6448796443.html	Black Lab Mix Female Dog Lost - ***$2,500 Reward***	\N	\N
26	\N	d	\N	\N	\N	\N	Black Lab Mix Female Dog 35 lbs - answers to Frida. She ran off from her dog walkers January 11th in McLaren Park in San Francisco.If you have found her or see that someone else has - please call or text with a picture and video. There is a $2,500 reward for her safe return.Her family misses her tremendously!!!Thank you!	2018-01-05 08:30:54.08	https://images.craigslist.org/00M0M_febfUEmmkjj_600x450.jpg	\N	\N	{}	https://sfbay.craigslist.org/sfc/laf/d/black-lab-mix-female-dog-lost/6448794284.html	Black Lab Mix Female Dog Lost - ***$2,500 Reward***	\N	\N
27	\N	c	\N	\N	\N	\N	My companion Nala went missing on Jan.1.2018. She is a indoor cat and is skinny because she is old. No collar but she is chipped. Please help her get back home. She is a simeese sealLint long hair femal cat. Yes she is spayed and again chipped.	2018-01-03 16:51:33.08	https://images.craigslist.org/00V0V_orHpuvlMMw_600x450.jpg	38.0031	-121.9172	 (pittsburg / antioch)	https://sfbay.craigslist.org/eby/laf/d/lost-simeese/6447093997.html	Lost simeese	\N	\N
28	\N	c	\N	\N	\N	\N	I'm still searching for my beloved gray-and-white tuxedo tabby cat, Timothy Leadbelly.Gone missing in Walnut Creek but that was many months ago, so he could be anywhere by now - but I've heard firsthand reports of cats that have been found, or come home, after two years or more. Recently a cat in wine country was reunited with its family after having gone missing ten years ago. I'm not giving up!!!I am offering a large REWARD for his return or reliable information leading to his recovery.Key traits ---- large size-- dark striping on gray background-- tuxedo pattern -- white chin, chest, paws, stomach ...but no white on sides or back-- green eyes-- pale-pink nose with a vertical, somewhat triangular blaze of white fur above-- usually shy, but may respond to the mealtime call 'Fressssh kitty crunchies, fressssh crunchies!'Note -- if you approach him while he's on a fence or other high surface, he may try to walk across the length of your outstretched arm -- a habit I indulged him in.Any leads, tips, help welcome.thank you for reading!keywords -- cat kitty gray grey tabby dark stripes striping black white male neutered lost missing abandoned feral Walnut Creek Jones Parkside Oak Civic Keys BART Putnam Pleasant Hill Contra Costa Canal Trail Albany El Cerrito San Francisco Bay East Bay	2017-12-25 10:53:49.08	https://images.craigslist.org/00R0R_lUH5ttBF0Uf_600x450.jpg	37.9182	-122.0717	 (Anywhere in SF Bay Area)	https://sfbay.craigslist.org/eby/laf/d/still-searching-for-my/6437413512.html	Still Searching for My Beloved Timothy Leadbelly	\N	\N
29	\N	c	\N	\N	\N	\N	Lost cat! just doesn't cut it. Your ad would be more productive if you include something descriptive.	2017-12-26 21:56:42.08	\N	37.5	-122.25	{}	https://sfbay.craigslist.org/eby/laf/d/include-color-gender-breed-in/6438891333.html	Include color, gender, breed in your title for lost/found pets	\N	\N
30	\N	d	\N	\N	\N	\N	Nala has been missing since 8/25/2016. She is a 7 year old, 8 lb. female and spayed Shih Tzu mix. Her main color is cream with some light gray in the face, ears, back and tail.  She has a microchip.  She was lost near Trieste Ct. and Oswego drive in San Jose. We miss her badly and reward will be given with no questions ask.  E-mail Ness or call/text at (4-zero-8)256-7000.  PLEASE HELP!	2018-01-06 06:41:54.08	https://images.craigslist.org/00i0i_ZQcaDYfQah_600x450.jpg	37.322841	-121.852664	Trieste Ct. at Oswego Dr.	https://sfbay.craigslist.org/sby/laf/d/reward-for-return-of-lost/6449843586.html	$5,000.00 REWARD FOR RETURN OF LOST/MISSING DOG (SHIH TZU MIX)	\N	\N
31	\N	d	\N	\N	\N	\N	Nala has been missing since 8/25/2016. She is a 7 year old, 8 lb. female and spayed Shih Tzu mix. Her main color is cream with some light gray in the face, ears, back and tail.  She has a microchip.  She was lost near Trieste Ct. and Oswego drive in San Jose. We miss her badly and reward will be given with no questions ask.  E-mail Ness or call/text at (4-zero-8)256-7000.  PLEASE HELP!	2018-01-06 06:43:39.08	https://images.craigslist.org/00i0i_ZQcaDYfQah_600x450.jpg	37.322841	-121.852664	Trieste Ct. at Oswego Dr.	https://sfbay.craigslist.org/sby/laf/d/reward-for-return-of-lost/6449845359.html	$5,000.00 REWARD FOR RETURN OF LOST/MISSING DOG (SHIH TZU MIX)	\N	\N
32	\N	d	\N	\N	\N	\N	*REWARD*Lost DogGerman Wired Hair breed - brown dog with reddish beardOdin has been missing since the evening of 1/1/18. Last seen running around Serres Ranch in Northern Sonoma on Highway 12, near Madrone Road. Odin was wearing two collars, one green and one orange. Neither have tags.He is an intact, male, microchipped and he has a tattoo within his earlobe reading: 230095. He is VERY friendly and he is my son's best friend. We are desperate for his safe return.Please contact; or with ANY information.	2018-01-06 12:55:25.08	\N	38.338559	-122.493782	16060 Highway 12	https://sfbay.craigslist.org/nby/laf/d/reward-lost-dog/6450336678.html	REWARD - LOST DOG	\N	\N
33	\N	d	\N	\N	\N	\N	"HONEYBEAR" DISAPPEARED LAST NIGHT AROUND 830 PM. AT MY PLACE ON LOUIS KROHN DR AND WE CANT FIND HER. I. HOPING SHE GOT FOUND BY A NICE PERSON AND IS LOOKING FOR ME.I AM FOSTERING HER, HER OWNER IS 85 AND GOT ADMITTED TO A GROUP HOME.SHE IS PARTIALLY BLIND, AND MOSTLY DEAF. SHE IS UMDER WEIGHT BUT VERY HEALTHY. PLEASE CALL ME IF U HAVE HER OR SEEN HER...	2018-01-06 17:59:52.08	https://images.craigslist.org/00D0D_iU9sCogHzDr_600x450.jpg	38.426286	-122.760519	4078 Louis krohn dr	https://sfbay.craigslist.org/nby/laf/d/lost-my-dog/6450631720.html	Lost my dog	\N	\N
36	\N	d	\N	\N	\N	\N	Nala has been missing since 8/25/2016. She is a 7 year old, 8 lb. female and spayed Shih Tzu mix. Her main color is cream with some light gray in the face, ears, back and tail.  She has a microchip.  She was lost near Trieste Ct. and Oswego drive in San Jose. We miss her badly and reward will be given with no questions ask.  E-mail Ness or call/text at (4-zero-8)256-7000.  PLEASE HELP!	2018-01-07 08:15:51.08	https://images.craigslist.org/00i0i_ZQcaDYfQah_600x450.jpg	37.322841	-121.852664	Trieste Ct. at Oswego Dr.	https://sfbay.craigslist.org/sby/laf/d/reward-for-return-of-lost/6451004999.html	$5,000.00 REWARD FOR RETURN OF LOST/MISSING DOG (SHIH TZU MIX)	\N	\N
37	\N	d	\N	\N	\N	\N	LOST DOG- STELLA.  LAST SEEN 1/6 AROUND STRAWBERRY SPIT IN HARBOR POINT AREA OF MILL VALLEY.  VERY SKITTISH.  IF YOU SEE HER, PLEASE LET US KNOW.  IF YOU SIT AND CALL HER NAME, SHE MAY COME TO YOU.	2018-01-07 08:37:01.08	\N	37.883826	-122.501984	STRAWBERRY at WEATHERLY	https://sfbay.craigslist.org/nby/laf/d/lost-dog-stella-chihuahua-mix/6451027092.html	LOST DOG- STELLA- CHIHUAHUA MIX	\N	\N
38	\N	d	\N	\N	\N	\N	STELLA RAN OUT OF THE HOUSE YESTERDAY AROUND NOON IN CORTE MADERA.  SHE MAY HAVE MADE IT BACK TO SAN FRANCISCO. VERY SKITTISH- IF YOU SIT AND CALL HER SHE MAY COME TO YOU.  LAST SEEN IN STRAWBERRY AT STRAWBERRY AND WEATHERLY IN MILL VALLEY AREA.	2018-01-07 08:40:51.08	\N	37.883254	-122.498074	STRAWBERRY at WEATHERLY	https://sfbay.craigslist.org/sfc/laf/d/lost-dog-stella-chihuahua-mix/6451030942.html	LOST DOG- STELLA- CHIHUAHUA MIX-15 LBS-TAN WITH BLACK NOSE AND COLLAR	\N	\N
39	\N	d	\N	\N	\N	\N	This search is active.SAN PABLO - An adult female Mini husky has been missing since Nov 25th near SAN PABLO AVE and RUMRILL.She is small 14 pounds, full grown.We have several sightings along San Pablo Ave but have not been able to find her.She has a microchip and a tag license.REWARD!!! No questions asked.If you see her, please try to get a pic and text or call.	2018-01-07 18:08:46.08	https://images.craigslist.org/00N0N_j2L0C6UF30Q_600x450.jpg	37.9724	-122.3369	{}	https://sfbay.craigslist.org/eby/laf/d/lost-dog-mini-husky-reward/6451629016.html	LOST DOG MINI HUSKY REWARD$$$!!!	\N	\N
40	\N	d	\N	\N	\N	\N	Missing since: New Year's EveLast seen: Near Morgan Hill Library$$$ REWARD $$$Please help us and keep an eye out. This is Willa. She got spooked on NYE and is lost.She ran from the Morgan Hill library area just after midnight. She is 8 years old, about 6 pounds, reddish brown,  min-pin / chihuahua mix. She is skittish but friendly.Willa is a family dog and is very missed, especially by the kiddos.She is chipped, we put up flyers and have been to all of the shelters.  THANK YOU SO MUCH.	2018-01-04 08:42:09.08	https://images.craigslist.org/00i0i_5Da5M1CxmE7_600x450.jpg	37.124945	-121.660757	Alkire at Peak	https://sfbay.craigslist.org/sby/laf/d/reward-lost-dog-female-brown/6447635681.html	REWARD! LOST DOG - Female Brown Min Pin Chihuahua	\N	\N
41	\N	d	\N	\N	\N	\N	My baby has been missing since August 21st 2017. He is 14years old, microchipped, was wearing a black collar that says West Coast Offshore with tags that current. If you see him PLEASE contact me at. He has major health problems as well as does have some missing teeth from old age and needs to be on his medication!! REWARD if found !!Its been 3 months now &  I cant stop thinking about my boy I know he's out there somewhere.. I miss him terribly !! Thank you to everyone that has emailed me or called me helping to find my little guy ! If you have him please return him to me NO questions asked my baby needs his medication. His hair was medium length when he went missing.	2018-01-08 10:49:15.08	\N	\N	\N	 (fremont / union city / newark)	https://sfbay.craigslist.org/eby/laf/d/lost-stolen-miniature/6452332452.html	LOST/ STOLEN MINIATURE SCHNAUZER DOG	\N	\N
42	\N	d	\N	\N	\N	\N	My baby has been missing since August 21st 2017. He is 14years old, microchipped, was wearing a black collar that says West Coast Offshore with tags that current. If you see him PLEASE contact me at. He has major health problems as well as does have some missing teeth from old age and needs to be on his medication!! REWARD if found !!Its been 3 months now &  I cant stop thinking about my boy I know he's out there somewhere.. I miss him terribly !! Thank you to everyone that has emailed me or called me helping to find my little guy ! If you have him please return him to me NO questions asked my baby needs his medication. His hair was medium length when he went missing.	2018-01-02 17:33:21.08	\N	\N	\N	 (fremont / union city / newark)	https://sfbay.craigslist.org/eby/laf/d/lost-stolen-miniature/6445933552.html	LOST/ STOLEN MINIATURE SCHNAUZER DOG	\N	\N
43	\N	d	\N	\N	\N	\N	Our dog got out on new years eve due to all of the loud fireworks/gun shots. It's been five days now of searching every dog pound in the area and searching the streets trying to find our baby boy . He is a 6 years old American pit bull brown and white and he is wearing a purple collar with orange on it	2018-01-05 23:09:04.08	https://images.craigslist.org/00I0I_i5zy6hmq8wt_600x450.jpg	38.1053	-122.2474	 (Vallejo ca)	https://sfbay.craigslist.org/sby/laf/d/lost-dog-reward/6449682930.html	Lost dog *reward	\N	\N
44	\N	d	\N	\N	\N	\N	Theo ran away from the dog sitters at 5pm on 2/13 He was last seen at 1146 Blossom Hill Road In San Jose, Ca. 95118. Any information or if you think you've seen him:Please email/call/text Jim at or reply to this email. NO QUESTIONS ASKED! $3,500 REWARD.WE JUST WANT HIM HOME! god bless!> Brussels Griffon (Black & Tan) Looks like Yorkie> Male> Microchipped> Approx. 10 Pounds> 1 Years Old> Pug-like Nose> Snaggle Tooth> Docked Tail> Old wound on back> Theodo NOT contact me with unsolicited ser	2018-01-09 15:42:43.08	https://images.craigslist.org/00707_761eJbSFQcS_600x450.jpg	37.8471	-122.2223	{}	https://sfbay.craigslist.org/nby/laf/d/brussels-griffon-dog-looks/6453969487.html	BRUSSELS GRIFFON Dog (Looks like Yorkie) LOST! $3,500 REWARD!	\N	\N
45	\N	d	\N	\N	\N	\N	Our beloved Theo has been missing since February 13th. He is our baby. We just want him back. Please PLEASE Call or text or reply to this email. NO QUESTIONS ASKED!!! REWARD $3,500 PLEASE CALL/TEXT JIM:Theo ran away from the dog sitters at 5pm on 2/13 He was last seen at 1146 Blossom Hill Road In San Jose, Ca. 95118. Any information or if you think you've seen him:WE JUST WANT HIM HOME! god bless!> Brussels Griffon (Black & Tan) Looks like Yorkie> Male> Microchipped> Approx. 10 Pounds> 1 Years Old> Pug-like Nose> Snaggle Tooth> Docked Tail> Old wound on back> Theo	2018-01-09 15:42:31.08	https://images.craigslist.org/00707_761eJbSFQcS_600x450.jpg	37.2458	-121.8306	 (los gatos)	https://sfbay.craigslist.org/sby/laf/d/3500-reward-for-the-return-of/6453969270.html	$3500 Reward for the return of our Missing Brussels Griffon DOG	\N	\N
46	\N	d	\N	\N	\N	\N	Our beloved Theo has been missing since February 13th. He is our baby. We just want him back. Please PLEASE Call or text or reply to this email. NO QUESTIONS ASKED!!! REWARD $3,500 PLEASE CALL/TEXT JIM:Theo ran away from the dog sitters at 5pm on 2/13 He was last seen at 1146 Blossom Hill Road In San Jose, Ca. 95118. Any information or if you think you've seen him:WE JUST WANT HIM HOME! god bless!> Brussels Griffon (Black & Tan) Looks like Yorkie> Male> Microchipped> Approx. 10 Pounds> 1 Years Old> Pug-like Nose> Snaggle Tooth> Docked Tail> Old wound on back> Theo	2018-01-09 15:42:13.08	https://images.craigslist.org/00707_761eJbSFQcS_600x450.jpg	37.2458	-121.8306	 (los gatos)	https://sfbay.craigslist.org/sby/laf/d/3500-reward-missing-dog/6453968979.html	$3,500 REWARD! Missing Dog! Brussels Griffon - looks like Yorkie	\N	\N
47	\N	d	\N	\N	\N	\N	Our beloved Theo has been missing since February 13th. He is our baby. We just want him back. Please PLEASE Call or text or reply to this email. NO QUESTIONS ASKED!!! REWARD $3,500 PLEASE CALL/TEXT JIM:Theo ran away from the dog sitters at 5pm on 2/13 He was last seen at 1146 Blossom Hill Road In San Jose, Ca. 95118. Any information or if you think you've seen him:WE JUST WANT HIM HOME! god bless!> Brussels Griffon (Black & Tan) Looks like Yorkie> Male> Microchipped> Approx. 10 Pounds> 1 Years Old> Pug-like Nose> Snaggle Tooth> Docked Tail> Old wound on back> Theo	2018-01-09 15:41:49.08	https://images.craigslist.org/00707_761eJbSFQcS_600x450.jpg	37.2458	-121.8306	 (los gatos)	https://sfbay.craigslist.org/sby/laf/d/have-you-seen-our-little-dog/6453968553.html	HAVE YOU SEEN OUR LITTLE DOG - Looks like yorkie - ? $3,500 REWARD!	\N	\N
48	\N	d	\N	\N	\N	\N	My roommates beautiful Australian Shepherd, female 6yo - name is Georgia - was lost by a family we left the dog with over the holidays. They offer dog housing services via Rover and lost her. They live here: 563 Rainwell Dr, San Jose. Please help me find her. She is a beautiful dog, picture attached, and is the sweetest dog ever. She's fast but responds to friendly calling of her name and loves rubs on her back. If you see her, please call me immediately -. Correct number, I'm a transplant from Charlotte. Her tags are to my roommate Jeff Evey. They say Maricopa, Arizona but she lives in Santa Clara. She is also chipped. I love this dog more than anything in California so any information or help would be greatly appreciated in her safe return to our home. Reward for her safe return. If you have her, please give her back. I'll negotiate. I love this dog and she is priceless to me. No questions asked.	2018-01-09 17:23:46.08	\N	\N	\N	 (san jose east)	https://sfbay.craigslist.org/sby/laf/d/lost-dog-3k-reward-australian/6454069721.html	Lost dog, $3k reward, Australian Shepherd, shepard, shephard, Aussie	\N	\N
49	\N	d	\N	\N	\N	\N	$3000 Reward, No questions askedOur Australian Shepherd named "Georgia" was lost while being boarded at Rover.Please keep a lookout for her we miss her terribly!She will normally come if you say "Georgia come here" and snap your fingers loudly. Probably is very skittish now.Her tags have my phone number on them. They are Maricopa (Arizona) tags but she lives in Santa Clara and was lost in San Jose.Thanks for your help finding our beloved friend!Australian Shepherd Sheperd Shephard Shepard Aussie	2018-01-09 18:25:58.08	https://images.craigslist.org/01414_e3YuBtuWhq0_600x450.jpg	37.3729	-121.856	 (san jose east)	https://sfbay.craigslist.org/sby/laf/d/lost-dog-lost-australian/6454123394.html	Lost Dog! Lost Australian Shepherd $3000 reward no questions asked	\N	\N
50	\N	d	\N	\N	\N	\N	Please help. This dog is from Castro Valley and was found last night in the rain. The person who found it  took it to his work in San Leandro on the way to the Oakland SPCA when it jumped out his car and he chased it for four blocks and could not catch it. His name is Rocky and he is nine years old. His family misses him!  Please call day or night if you see him!! Thank youPlease call Katie	2018-01-09 20:02:38.08	https://images.craigslist.org/00X0X_fY0aZkMWokZ_600x450.jpg	37.720237	-122.153356	Williams Avenue at Washington Boulevard	https://sfbay.craigslist.org/eby/laf/d/lost-dog-please-help-reward/6454192457.html	LOST DOG PLEASE HELP!  REWARD	\N	\N
51	\N	c	\N	\N	\N	\N	Hello friends! My sweet angel cat friend Jeana (Jay-nuh) went missing from Danbeck ave and Gay st in Santa Rosa on Monday January 1st. She is a seven year old female tabby, chipped and spayed. She was relocated from Carissa ave and Summerfield rd and may have gone back over there.She has a leopard print collar and a small but harmless and distinctive cyst near her left ear.Anyhow, she's my best friend and I've been putting up fliers and keeping my eye out for her. Any help in bringing her home would be greatly appreciated. Sweet Jeana is loved and missed.Thank you!!	2018-01-08 14:33:44.08	https://images.craigslist.org/00505_6ahcmQNgnoB_600x450.jpg	38.4534	-122.6878	 (santa rosa)	https://sfbay.craigslist.org/nby/laf/d/lost-kitty-girl-please-help/6452660513.html	Lost Kitty Girl. Please Help!	\N	\N
52	\N	c	\N	\N	\N	\N	My cat JUNIOR (a 4 year old male) hasn't returned home since 10/22/2017. He is white with gray/black spots on his body. He has 2 distinct spots that sit on top of both his ears. He has a tail that looks like a raccoon tail. He is very friendly and loves people! Last seen was near my home in Richmond. He is chipped and neutered. (in the picture his paw looks black but its very pink) He likes to be outside a lot. I AM OFFERING A REWARD FOR HIS RETURN !!! $$$$ If you do see him please give me a call: Wendy Thank you.	2018-01-08 15:01:10.08	https://images.craigslist.org/01717_dVOdStGQLu7_600x450.jpg	37.934095	-122.348535	 (richmond / point / annex)	https://sfbay.craigslist.org/eby/laf/d/has-anybody-seen-junior/6452694367.html	HAS ANYBODY SEEN JUNIOR ???	\N	\N
53	\N	d	\N	\N	\N	\N	3 easy steps to finding your lost pet or re-uniting a found pet with its owner. Take advantage of our FREE and/or paid services.We're here to help make sure you do everything reasonably possible to bring your lost dog or missing cat home.lost pet details	2017-12-18 00:49:02.08	\N	\N	\N	{}	https://sfbay.craigslist.org/pen/laf/d/lost-or-missing-dog-locating/6429565407.html	A lost or missing dog locating service...Our alert lost pet service	\N	\N
54	\N	d	\N	\N	\N	\N	3 easy steps to finding your lost pet or re-uniting a found pet with its owner. Take advantage of our FREE and/or paid services.We're here to help make sure you do everything reasonably possible to bring your lost dog or missing cat home.lost pet details	2017-12-18 00:48:30.08	\N	\N	\N	{}	https://sfbay.craigslist.org/eby/laf/d/lost-or-missing-dog-locating/6429565290.html	A lost or missing dog locating service...Our alert lost pet service	\N	\N
55	\N	d	\N	\N	\N	\N	3 easy steps to finding your lost pet or re-uniting a found pet with its owner. Take advantage of our FREE and/or paid services.We're here to help make sure you do everything reasonably possible to bring your lost dog or missing cat home.lost pet details	2017-12-18 00:49:28.08	\N	\N	\N	{}	https://sfbay.craigslist.org/pen/laf/d/lost-or-missing-dog-locating/6429565509.html	A lost or missing dog locating service...Our alert lost pet service	\N	\N
56	\N	c	\N	\N	\N	\N	Lost Siamese Cat male, 7 months old flame point heart broken.	2018-01-03 09:29:22.08	\N	38.008222	-122.641794	Carson at Madrone	https://sfbay.craigslist.org/nby/laf/d/lost-siamese-flame-point-cat/6446522744.html	Lost Siamese flame point cat	\N	\N
57	\N	c	\N	\N	\N	\N	An adult female dark Siamese cat with slightly noticeable stripes on top of her upper back head has been missing since July 19th around 2am on Lilac alley between 24th Street and 25th Street. It's very likely she has been stolen from us. She would never run away from us or stay out for a very long time. She is very scared of strangers and meows a lot. She is spayed and has a microchip.My family and I miss her so much by the day. She is very close to my cousin that has autism.If you found a Siamese adult cat and believe it's her. Take her to the animal shelter or animal hospital so that they can check on micro chip. If it's her. You will be rewarded. We want her back and the past holidays was the first holidays with her absence.	2018-01-03 10:07:09.08	\N	37.750935	-122.417779	Lilac	https://sfbay.craigslist.org/sfc/laf/d/my-siamese-cat-missing/6446579369.html	MY SIAMESE CAT MISSING 7-19-2017	\N	\N
58	\N	c	\N	\N	\N	\N	Please help!  Coco went missing the morning of 12/1/17. She is microchipped and has a purple flower tag with her name and our number. If anyone has seen her in your neighborhood, please contact us.Description: Tortoiseshell coloredAbout 1.5 yr oldHas a light blue collar with a bell, and a purple, flower shaped name tag with her name and our phone number.Is usually shy, but friendly	2018-01-03 20:51:54.08	https://images.craigslist.org/00T0T_gEKz8X9cgP8_600x450.jpg	37.548235	-121.94607	Ondina at Los Pinos Street	https://sfbay.craigslist.org/eby/laf/d/lost-tortoiseshell-cat/6447267124.html	LOST TORTOISESHELL CAT	\N	\N
59	\N	c	\N	\N	\N	\N	Will give money reward for return no questions asked.	2018-01-04 13:43:10.08	\N	37.7706	-122.2648	 (alameda)	https://sfbay.craigslist.org/eby/laf/d/lost-cat-ukulele/6448065475.html	Lost cat ukulele	\N	\N
60	\N	c	\N	\N	\N	\N	Reward! Please help, our cat Nala got away from our home near the intersection of Decoto Rd. and Fremont Blvd on Tuesday Dec 26. She is a brown/black tabby with white fur on face and underneath.  She is long and very agile, she is also very friendly.  There is a generous reward for ANY information that brings her back to us!Contact me, Henry, at this email address or text me at 408-two2one-7102.Thank you!	2018-01-04 16:19:12.08	https://images.craigslist.org/00k0k_5GmG03SrJ9N_600x450.jpg	37.570926	-122.032506	decoto rd at fremont blvd	https://sfbay.craigslist.org/eby/laf/d/lost-cat-near-decoto-and/6448237677.html	Lost Cat near Decoto and Fremont Blvd	\N	\N
61	\N	c	\N	\N	\N	\N	lost my cat October 20th. W SJ,   Race st, Auzeraiz ave.  Very friendly. name. "Cuz Cuz"Miss him alot	2018-01-04 22:39:48.08	https://images.craigslist.org/00101_cRjw5lEBQwp_600x450.jpg	37.316298	-121.916293	 (san jose west)	https://sfbay.craigslist.org/sby/laf/d/lost-catauzeraiz-ave-race-st/6448485501.html	lost Cat  10/17  Auzeraiz ave  x  Race st	\N	\N
62	\N	c	\N	\N	\N	\N	Lost female tortie cat, small, black brown and beige coloring.  Very sweet and friendly.  Lost in Soquel near Old San Jose Rd.	2018-01-04 23:11:31.08	\N	37.0048	-121.9507	 (soquel)	https://sfbay.craigslist.org/scz/laf/d/lost-tortie-cat/6448495177.html	Lost tortie cat	\N	\N
63	\N	c	\N	\N	\N	\N	I lost my cat tonite she lives at 1213 fell st it's a old fire house next to 76 gas station on fell and Divisadero Street. She got out as I left the door open for not even a few sec.s please call or bring her back home if anyone finds her . She is black with orange spots and stripes	2018-01-04 23:18:25.08	\N	37.774062	-122.437611	Fell st at Divisadero	https://sfbay.craigslist.org/sfc/laf/d/lost-cat-near-fell-st-and/6448497204.html	Lost cat near fell st and Divisadero	\N	\N
64	\N	c	\N	\N	\N	\N	Very sweet and social brown tabby boy named Bernard; last spotted around Christmas near his regular hangout by our house, in the Vistas/"the LOOP" area of Novato. He is very approachable, has a red collar with tags, and is also neutered and chipped. We are offering a reward to anyone who assists in the safe return, or leads us to the whereabouts of our kitty. We miss him and hope that if someone happened to pick him up, or even if you see him around, that you can give us a call as soon as you see him. Happy holidays to all, and thank you for your help.	2018-01-05 07:28:26.08	\N	38.0973	-122.5837	Grande vista at Novato blvd	https://sfbay.craigslist.org/nby/laf/d/lost-tabby-cat-reward/6448709719.html	Lost tabby cat REWARD	\N	\N
65	\N	c	\N	\N	\N	\N	Please help us find Kala. We are cat-sitting her for a friend from San Francisco and her chip is out of date.Age: 13FemaleIndoor cat, very friendly, should respond to the sound of her name and crunchy cat food.She left our home near Del Norte BART 12/29 and was last seen near Mira Vista Elementary School three days later.	2018-01-05 07:46:29.08	\N	37.939124	-122.315308	6397 Hazel Ave	https://sfbay.craigslist.org/eby/laf/d/lost-cat-big-fluffy-tortie/6448733082.html	Lost cat. Big fluffy tortie/white last seen near Mira Vista Elem.	\N	\N
66	\N	c	\N	\N	\N	\N	An adult female dark Siamese cat with slightly noticeable stripes on top of her upper back head has been missing since July 19, 2017 around 2am on Lilac alley between 24th Street and 25th Street. She has never done this before and we have owned her for over 9 years. She is very scared of strangers and meows a lot. She is spayed and has a microchip.There will be a reward to whoever has her and see she is not happy. I hope she is well care for until this day. Take her to the shelter or hospital to check micro chip. Will get your reward.	2018-01-05 11:42:37.08	\N	37.750935	-122.417779	Lilac	https://sfbay.craigslist.org/sfc/laf/d/my-siamese-cat-is-still/6449082757.html	MY SIAMESE CAT IS STILL MISSING!!! REWARD$$$!!!	\N	\N
67	\N	c	\N	\N	\N	\N	Prince was last seen at Rose wood apartments in Union City, Ca. He's a indoor cat but loves to go outside at night. He's not spayed. He has green eyes & is a gray tabby, domestic short hair. He's super friendly! He had a gray flea collar on & a tag with his name & information, it could have come off. He's loved & missed! Handsome reward if found. Please help me find my baby! Cross streets: Decoto Rd. & Skylark Dr. & Swan Ct.	2018-01-05 17:29:25.08	\N	37.584534	-122.019072	Skylark Dr at Swan Ct., Decoto Rd.	https://sfbay.craigslist.org/eby/laf/d/lost-cat/6449493755.html	Lost cat	\N	\N
68	\N	c	\N	\N	\N	\N	An adult female dark Siamese cat with slightly noticeable stripes on top of her upper back head. She has snowshoe but her two back legs are like white boots. She has been missing since July 19, 2017 around 2am on Lilac alley between 24th Street and 25th Street. She is micro chipped under our information. If you believe to have her to please go to an animal shelter or animal clinic so that they can check a micro chip on her. We have owned her for over 9 years. She is very scared of strangers and meows a lot. She is also a picky eater. So if you keep giving her food that she won't eat. She may die because we know what she likes.No questions asked if she is returned back to us. My family and I miss her so much.	2018-01-06 11:48:36.08	\N	37.751129	-122.418336	2869 Mission St	https://sfbay.craigslist.org/sfc/laf/d/my-siamese-cat-is-catnapped/6450248872.html	MY SIAMESE CAT IS CATNAPPED! REWARD!	\N	\N
69	\N	c	\N	\N	\N	\N	Chevy, our black male cat has disappeared in Kensington on Saturday December 30th. He is very nice and friendly but easily scared, so he might be hiding somewhere in your garden, yard or even under your car.Chevy is all black with green eyes and probably 6 months old, he is micro-chipped and has received all his shots.Thanks a million for your help.	2018-01-01 22:52:25.08	\N	37.8918	-122.2604	 (berkeley north / hills)	https://sfbay.craigslist.org/eby/laf/d/lost-black-cat-on-december/6444913125.html	Lost Black Cat on December 30th in Kensington	\N	\N
70	\N	c	\N	\N	\N	\N	Lost cat, black and white, female, 1.5 years, very friendly.Please call/text anytime. Reward.	2018-01-07 00:00:47.08	\N	36.965288	-121.987548	1630 Merrill St	https://sfbay.craigslist.org/scz/laf/d/lost-cat-reward/6450798963.html	Lost cat - REWARD	\N	\N
71	\N	c	\N	\N	\N	\N	An adult female dark Siamese cat with slightly noticeable stripes on top of her upper back head has been missing since July 19, 2017 around 2am on Lilac alley between 24th Street and 25th Street. She has never done this before and we have owned her for over 9 years. She is very scared of strangers and meows a lot. She is spayed and has a microchip. My family and I miss her so much that it has not been the same being at home.If you have her and or know someone that does to please contact me. No questions asked for her return.	2018-01-07 10:43:27.08	\N	37.750935	-122.417779	Lilac	https://sfbay.craigslist.org/sfc/laf/d/my-siamese-cat-is-still/6451171331.html	MY SIAMESE CAT IS STILL MISSING!!! REWARD$$$!!!	\N	\N
72	\N	c	\N	\N	\N	\N	Female, wearing red collar (with grey paw prints on it), missing since 8/4/16 from Buena Vista at Grand area. Very shy cat, long-hair, grey color. See photo please. She has a tiny white spot on her chest and the back half of body is kind of brownish color fur. She is micro chipped. Please call if you have seen her. Thank you very much.	2018-01-02 07:24:01.08	https://images.craigslist.org/00a0a_2QAZ77iLl3e_600x450.jpg	37.776261	-122.2541	Grand St at Buena Vista St	https://sfbay.craigslist.org/eby/laf/d/lost-cat-grey-long-hair/6445124609.html	LOST CAT, GREY, LONG-HAIR	\N	\N
73	\N	c	\N	\N	\N	\N	Boots is a 3 year old female longhaired(1/2 Maine Coon /Alleycat) cat who is mostly white and a dark brownish color. She has been missing since 9/29/2015, she is usually very friendly but probley is scared to death now being lost.She was hiding in a truck at night and got accidentally taken away from her family who loves and misses her greatly & needs her home again.She jumped out of the back window of a pickup truck on Summersville Rd. in Antioch in the Denny's Restaurant and Vallejo Gas Station area. She is spaded and is microchiped but it is registered to the NV Humane Society which is who fixed her originally. We had recently moved back here from Reno so Boots doesn't know this area at all. PLEASE help her come home where she is missed and loved so much, there is a reward offered for her return and you can give us a call ANYTIME 24/7 at: or	2018-01-07 12:13:23.08	\N	\N	\N	 (pittsburg / antioch)	https://sfbay.craigslist.org/eby/laf/d/still-missing-cat-boots/6451279415.html	STILL MISSING CAT "BOOTS"	\N	\N
74	\N	c	\N	\N	\N	\N	Have you seen this feral cat?  I have been feeding her for years.  Last saw her Dec 26 on Monmouth Drive in Milpitas in the morning.  Have not seen her since.  If you have seen her, or know where she is please contact me.  I have been trying to catch her as she needs to see a Vet as she may have ear cancer..Thank you for your help..	2018-01-01 19:29:14.08	https://images.craigslist.org/00a0a_kC33HU25pCW_600x450.jpg	\N	\N	 (milpitas)	https://sfbay.craigslist.org/sby/laf/d/lost-white-cat-with-bad-ear/6444824008.html	Lost White Cat with bad ear	\N	\N
75	\N	c	\N	\N	\N	\N	Our seven year old outdoor-access cat named Boots has not been home since Saturday, August 5th. He is a neutered male, medium sized long haired cat with black tiger stripes, black/brown coat and four white paws and white "tuxedo" belly. He is very familiar with the Louvaine Drive/Washington Street area of Broadmoor having lived here for several years, but could have ventured further away onto Sweetwood, 87th, St. Francis area, etc. He is very skittish and will hide in silence.REWARD OFFERED for his safe return, worried family appreciates your help.Please let me know if you see him so I know that he is ok and if possible, take a photo so I can identify it is him..	2018-01-01 18:45:21.08	\N	\N	\N	 (daly city)	https://sfbay.craigslist.org/pen/laf/d/lost-cat-male-brown-white/6444796425.html	Lost Cat - Male Brown/White/Black Long Hair - Last Seen 8/5 - REWARD	\N	\N
76	\N	c	\N	\N	\N	\N	My 6 year old Calico/Tortoiseshell cat went missing.  She is small, a mix of black and orange markings with white mittens, socks, and a white chest/neck. We live on Paru, between Clinton and Dayton Ave.  Please keep an eye out and call or text me if she is sighted or you have any knowledge of what may have happened to her.  There have been some possible sightings near Saint Charles between San Antonio and Santa Clara Ave as well as further up near Chestnut. When I have her back this post (and posters around the neighborhood) will be removed.  Thanks for your help.*REWARD* offered for her safe return!Also (to those whom this applies to): Please stop sending me advertisements in response to my request for help.	2018-01-08 00:42:32.08	https://images.craigslist.org/00Y0Y_ln5ysolEfPM_600x450.jpg	37.766728	-122.26228	Paru Street at Clinton Ave	https://sfbay.craigslist.org/eby/laf/d/missing-sm-calico-cat-spayed/6451810865.html	*MISSING* Sm, F Calico Cat, Spayed, REWARD!	\N	\N
77	\N	c	\N	\N	\N	\N	My 6 year old Calico/Tortoiseshell cat is missing. She is small, a mix of black and orange markings with white mittens, socks, and a white chest/neck. We live in Alameda, between Clinton and Dayton Ave, but I am considering the possibility that she may have been accidentally transported out of the city. Please keep an eye out and call or text me if she is sighted or you have any knowledge of what may have happened to her. When I have her back this post will be removed. Thanks for your help.*REWARD* offered for her safe return!	2018-01-08 00:42:20.08	https://images.craigslist.org/00K0K_7Y1GhDk3wYX_600x450.jpg	\N	\N	 (berkeley)	https://sfbay.craigslist.org/eby/laf/d/missing-sm-calico-cat-spayed/6451810823.html	*MISSING* Sm, F Calico Cat, Spayed, REWARD!	\N	\N
78	\N	c	\N	\N	\N	\N	Our cat Packy was last seen on 10/11/17 on the west side of Sacramento between Channing & Bancroft.He's a long-haired Himalayan/Siamese, male, neutered, 10 years old, no collar.Packy went missing three days after we evacuated to Berkeley from our Santa Rosa house, which burned down in the fires. Please, please help us find him. Please call/text JoAnn at if seen. Thank you!REWARD!	2017-12-28 08:26:51.08	https://images.craigslist.org/00i0i_1DLsm0SNC6i_600x450.jpg	37.864707	-122.281716	Sacramento at Channing Way	https://sfbay.craigslist.org/eby/laf/d/lost-cat-himalayan-siamese/6440463314.html	LOST CAT: Himalayan/Siamese, long-haired. REWARD!	\N	\N
79	\N	c	\N	\N	\N	\N	LONG-HAIR FEMALE CALICO cat missing SINCE 10/29/17. APPROXIMATELY 7-9 POUNDS. GREEN EYES. MICROCHIPPED. Approximately 8 years old. Nervous around people. NON-AGGRESSIVE. Responds to ATHENA. PLEASE HELP - ANY INFORMATION APPRECIATED.	2018-01-09 19:31:10.08	https://images.craigslist.org/00101_eJyKaJdMjFZ_600x450.jpg	37.5671	-122.3676	 (san mateo)	https://sfbay.craigslist.org/pen/laf/d/lost-female-calico-cat-please/6454172047.html	LOST FEMALE CALICO CAT - PLEASE HELP	\N	\N
80	\N	c	\N	\N	\N	\N	An adult female dark Siamese cat with slightly noticeable stripes on top of her upper back head has been missing since July 19, 2017 around 2am on Lilac alley between 24th Street and 25th Street. We have owned her for over 9 years. She is very scared of strangers and meows a lot. She is spayed and has a microchip.No questions asked if she is returned back to us or if you believe to have a Siamese cat that does not belong to you to please get her checked at an animal shelter or animal hospital for free micro chip being checked on her. My family and I miss her so much.	2018-01-09 19:38:57.08	\N	37.7509	-122.4153	Lilac Street between 24th Street and 25th Street	https://sfbay.craigslist.org/sfc/laf/d/reward-for-missing-siamese-cat/6454177369.html	REWARD FOR MISSING SIAMESE CAT	\N	\N
81	\N	c	\N	\N	\N	\N	Please help find the lost tan cat and a lost grey cat. The tan cat name is Ginger and she is pregnant. The grey cat is Bonnie. I moved them to my house on saratoga ave near the Immanuel Lutheran Church and they ran off. Please keep an eye out for them thank you. Please call. Or.	2018-01-09 20:14:27.08	https://images.craigslist.org/00G0G_l5bMmIHxty0_600x450.jpg	37.2713	-122.0227	 (saratoga)	https://sfbay.craigslist.org/sby/laf/d/missing-lost-tan-cat-pregnant/6454199505.html	Missing lost tan cat pregnant and grey cat	\N	\N
82	\N	c	\N	\N	\N	\N	Missing large grey and white fluffy kitty, 8 years old and male. Reward for any information leading to his recovery. His name is Kirby Sinclair and we've had him since he was a little kitten off of a farm. He went missing the morning of Tuesday, January 2 in Mill Valley near Hauke Park. Do you have any information about him? Did someone pick him up, thinking he was lost? Did he get accidentally locked in your garage or crawl space? Injured and hiding in your backyard? Please, please help us get him home! He is so loved and we are worried sick.	2018-01-09 22:49:28.08	https://images.craigslist.org/00F0F_baRhzpM4gPL_600x450.jpg	37.898725	-122.523286	Millay Place at Roque Moraes Drive	https://sfbay.craigslist.org/nby/laf/d/lost-gray-and-white-cat/6454269984.html	LOST GRAY AND WHITE CAT! Please help! Reward!	\N	\N
83	\N	c	\N	\N	\N	\N	Normally she is very wary of people and will probably run if approached.Slender girl with medium length hair.  3 yrs 8 mos old.  Her color is SMOKY GREY with some tan and  orange scattered on her coat.  Big Yellow Eyes.  Coat colors called Dilute Calico (or Dilute Tortie).  She has been missing so long she could look pretty rough by now, and could be anywhere. Vanished from her Fremont home on 8/31/17.    Is microchipped for ID.If you see her, or know where she might be please call Karen.  It would be a miracle to have her back home.  Reward available if you can help her get home.     THANKS	2017-12-29 21:12:57.08	https://images.craigslist.org/00d0d_74TPueRtoou_600x450.jpg	37.534896	-121.943092	Valorie St at Chadbourne/Olive	https://sfbay.craigslist.org/eby/laf/d/still-want-to-find-lost-cat/6442347779.html	Still Want to Find LOST CAT  Grey Dilute Calico	\N	\N
84	\N	c	\N	\N	\N	\N	My orange tabby cat has been missing for the past 2 weeks. He's domestic, mostly indoors and has long hair.Last seen on Humboldt Rd, Brisbane.Please call or email me if you've seen him!	2018-01-09 23:29:59.08	https://images.craigslist.org/00303_kRacwFFGnlK_600x450.jpg	37.683209	-122.406857	 (brisbane)	https://sfbay.craigslist.org/pen/laf/d/lost-orange-cat/6454281729.html	Lost Orange Cat	\N	\N
85	\N	c	\N	\N	\N	\N	I was attempting to imprint a feral cat, Roxy, to a friends backyard in Gilroy and after six weeks she was released. Unfortunately, Roxy didn't stay and hopped the fence and hasn't been seen since. Normally six weeks should be enough to imprint a cat, but for some reason Roxy didn't stay. So now I'm worried about whether she is safe and able to access some food or water. My friend and I continue to search for her, asking neighbors if they have seen her, leaving food out, etc., but no clues so far. Roxy is a light calico and tabby cat and has her left ear tipped. My friend lives not far from some farms near north end of Gilroy, so it's possible Roxy could have roamed in that area. Roxy is microchipped too. Unfortunately, I don't have any pictures of her. She is very skittish though and won't come up to you, but if she's hungry she may stay around if someone is feeding her, or there's a food source somewhere.If you see Roxy, or think you have seen her, please contact me and let me know. We would like to get her back safe and find an alternative set up for her so this doesn't happen again.Thanks	2018-01-09 23:41:41.08	\N	\N	\N	 (gilroy)	https://sfbay.craigslist.org/sby/laf/d/missing-calico-and-tabby/6454284718.html	MISSING: Calico and Tabby Feral Cat	\N	\N
86	\N	c	\N	\N	\N	\N	I was attempting to imprint a feral cat, Roxy, to a friends backyard in Gilroy and after six weeks she was released.  Unfortunately, Roxy didn't stay and hopped the fence and hasn't been seen since.  Normally six weeks should be enough to imprint a cat, but for some reason Roxy didn't stay.  So now I'm worried about whether she is safe and able to access some food or water.  My friend and I continue to search for her, asking neighbors if they have seen her, leaving food out, etc., but no clues so far.  Roxy is a light calico and tabby cat and has her left ear tipped.  My friend lives not far from some farms near north end of Gilroy, so it's possible Roxy could have roamed in that area.  Roxy is microchipped too.  Unfortunately, I don't have any pictures of her.  She is very skittish though and won't come up to you, but if she's hungry she may stay around if someone is feeding her, or there's a food source somewhere.If you see Roxy, or think you have seen her, please contact me and let me know.  We would like to get her back safe and find an alternative set up for her so this doesn't happen again.Thanks	2018-01-03 02:22:41.08	\N	\N	\N	 (gilroy)	https://sfbay.craigslist.org/sby/laf/d/missing-calico-and-tabby/6446170675.html	MISSING:  Calico and Tabby Feral Cat	\N	\N
87	\N	c	\N	\N	\N	\N	Mitzi disappeared near Cabrillo College roughly 2 years ago. She was the best cat I ever owned. I grew up with her. Very sweet, but can be shy of strangers. Would be around 12-14 years. I've given up most hope at this point, but you never know. She is very well loved and I miss her dearly.Chocolate point Himalayan, microchipped (we moved so address and phone number listed are not accurate), female, spayed.REWARDPlease contact me with any details, even bad news. Knowing is better than nothing.	2018-01-09 23:54:09.08	https://images.craigslist.org/00I0I_5A9bkcVsjqu_600x450.jpg	36.988705	-121.933126	jason ct	https://sfbay.craigslist.org/scz/laf/d/mitzi-himalayan-cat-still/6454287719.html	"Mitzi" Himalayan cat still missing since 2015. Long shot, I know.	\N	\N
88	\N	c	\N	\N	\N	\N	All gray, young cat, and very skittish. Cannot catch. Was spooked by visiting dogs on Christmas Eve and ran over fence. No collar. If seen, please call!	2018-01-10 13:00:52.08	\N	37.009133	-121.602859	7912 Cobblestone Court	https://sfbay.craigslist.org/sby/laf/d/lost-young-gray-cat-near/6455008808.html	Lost Young Gray Cat near Santa Teresa and 3rd	\N	\N
89	\N	c	\N	\N	\N	\N	An adult female dark Siamese cat with slightly noticeable stripes on top of her upper back head has been missing since July 19, 2017 around 2am on Lilac alley between 24th Street and 25th Street. I have a feeling someone has taken her from us. She is very scared of strangers and meows a lot. She is a very picky eater. Micro chipped and spayed. If you know someone that might have my cat or you may have my cat. Please go to any animal shelter or animal hospital to check on micro chip. Thanks!	2018-01-10 17:00:51.08	\N	37.750935	-122.417779	Lilac	https://sfbay.craigslist.org/sfc/laf/d/missing-siamese-cat/6455292560.html	MISSING SIAMESE CAT!	\N	\N
\.


--
-- Name: lostpets_lost_pet_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cristina
--

SELECT pg_catalog.setval('lostpets_lost_pet_id_seq', 89, true);


--
-- PostgreSQL database dump complete
--

